.travis.yml
Renaming production to staging
=> New branch organization

d3a_interface/utils.py
Outsourcing modules iterator as it will be used in both `d3a` and `d3a-api-client`
=> Outsourced modules iterator to d3a-interface

.pylintrc
Add a `.pylintrc` configuration file to automatically lint the code.
=> New pylintrc configuration file

.gitignore, d3a_interface/constants_limits.py, d3a_interface/device_validator.py, d3a_interface/schemas.py, d3a_interface/sim_results/device_statistics.py, tests/test_device_validator.py, tox.ini
Implement features for the new Home Meter device that should be used by both d3a and d3a-web.
- gridsingularity/d3a#1159
=> D3ASIM-3353: implement Home Meter device

.coveragerc, .github/workflows/d3a-interface_ci.yaml, .gitignore, README.md, codecov.yml, tox.ini
- Add Codecov coverage checks to CI
- Add coverage badge in README
- refactor tox configuration (remove unused environments and refactor inherited parameters)
=> D3ASIM-3461: Add coverage checks to CI

d3a_interface/validators/__init__.py, d3a_interface/validators/base_validator.py, d3a_interface/validators/cep_validator.py, d3a_interface/validators/finite_diesel_generator_validator.py, d3a_interface/validators/home_meter_validator.py, d3a_interface/validators/infinite_bus_validator.py, d3a_interface/validators/load_validator.py, d3a_interface/validators/market_maker_validator.py, d3a_interface/validators/pv_validator.py, d3a_interface/validators/storage_validator.py, d3a_interface/validators/utils.py, tests/test_device_validator.py
This PR unifies the validators interface. This potentially allows to remove code duplication and to simplify the creation of new validators in the future.
=> Refactor validators to implement a common interface

.github/workflows/d3a-interface_ci.yaml, .github/workflows/d3a-interface_ci_cd_development.yaml, .github/workflows/d3a-interface_ci_cd_staging.yaml
github actions slack notifications
=> DEV-87: github actions slack notifications

.github/workflows/d3a-interface_ci.yaml
=> DEV-93: Remove CI slack notifications

gsy_framework/constants_limits.py, gsy_framework/matching_algorithms/pay_as_clear_matching_algorithm.py, gsy_framework/settings_validators.py, gsy_framework/sim_results/__init__.py, gsy_framework/sim_results/bills.py, gsy_framework/sim_results/cumulative_grid_trades.py, gsy_framework/sim_results/energy_trade_profile.py, gsy_framework/utils.py, tests/test_settings_validators.py
Please review this through commits. The relevant changes are just a bunch of lines, while the rest is linting and imports fixes.
=> D3ASIM-3553: Rename Inter Area Agent to Market Agent

setup.cfg, setup.py
=> Bump version: 1.1.0 → 1.2.0

gsy_framework/sim_results/cumulative_grid_trades.py, gsy_framework/utils.py
Actual bug fix is in 300e34f162d2ed487c5ccea462975e5ccc5d303a
Also adapted to pylint warnings and had to disable two of them, which would have lead to global refactoring of the results accumulation which should be targeted in a separate story. Shall I create a ticket for this?
=> Bug/gsye 214 Fix bug in CumulativeGridTrades

setup.cfg, setup.py
**INTEGRATION_TESTS_BRANCH**=master
=> Bump version: 1.2.0 → 1.3.0

tests/test_matching_algorithms/__init__.py, tests/test_matching_algorithms/test_attributed_matching_algorithm.py, tests/test_matching_algorithms/test_preferred_partners_matching_algorithm.py
Created a unit test for preferred trading partners that tests the full flow of the algorithm, and another one for the green energy.
=> GSYE-327: Added unit tests for the attributed matching algorithm.

gsy_framework/utils.py
Related PR:
https://github.com/gridsingularity/gsy-web/pull/1737
=> GSYE-335: Add is_valid_uuid into utils

.github/workflows/gsy-framework_ci.yaml
=> DEV-250: remove branches

gsy_framework/sim_results/kpi.py, gsy_framework/sim_results/kpi_calculation_helper.py, gsy_framework/sim_results/scm/kpi.py
As requested by [GSYE-470](https://gridsingularity.atlassian.net/browse/GSYE-470), we want to group KPI-related calculations into a single module.
The following ticket should be done after this PR is merged:
https://gridsingularity.atlassian.net/browse/GSYE-477
=> GSYE-470: Apply DRY to calculation of some KPI statistics

gsy_framework/constants_limits.py, gsy_framework/schemas.py, gsy_framework/validators/__init__.py, gsy_framework/validators/heat_pump_validator.py
=> GSYE-428: Add HeatPump to ScenarioSchemas

.github/workflows/gsy-framework_ci.yaml, gsy_framework/community_datasheet/community_datasheet_parser.py, gsy_framework/community_datasheet/enums.py, gsy_framework/default_cds_downloader.py
=> GSYE-850: Move DefaultCommunityAreaNames to separate module

gsy_framework/sim_results/carbon_emissions/results.py
=> GSYE-859: Add cache to geopy library.

gsy_framework/read_user_profile.py
=> Added logs in order to further debug the production env.

gsy_framework/read_user_profile.py
=> Caught exception and reraised with extra profile information.

gsy_framework/read_user_profile.py
=> Removed logs from read_arbitrary_profile method.

gsy_framework/constants_limits.py
=> GSYE-871: Add constants for profile keys in scenario
