gridsingularity/gsy-framework

- d3a_interface/sim_results/__init__.py
- d3a_interface/sim_results/aggregate_results.py
- d3a_interface/sim_results/all_results.py
- d3a_interface/sim_results/area_throughput_stats.py
- d3a_interface/sim_results/bills.py
- d3a_interface/sim_results/cumulative_grid_trades.py
- d3a_interface/sim_results/cumulative_net_energy_flow.py
- d3a_interface/sim_results/device_statistics.py
- d3a_interface/sim_results/energy_trade_profile.py
- d3a_interface/sim_results/export_unmatched_loads.py
- d3a_interface/sim_results/kpi.py
- d3a_interface/sim_results/market_price_energy_day.py
- d3a_interface/sim_results/results_abc.py
- d3a_interface/utils.py
Potential improvement: currently the unit tests for the results classes are located either in d3a or in d3a-web, one more improvement to the process would be to port these to the d3a-interface, so that the code is tested in the same repo that it is created.
> Feature/d3asim 3307 Created an interface for the results classes. Added a manager class for all the simulation result objects. 

- d3a_interface/area_validator.py
- d3a_interface/constants_limits.py
- d3a_interface/scenario_validators.py
- tests/test_area_validator.py
- tests/test_scenario_validator.py
The simulation results that can be downloaded by the users contain a directory structure based on the names of the areas in the scenario. If these names contain invalid characters (like `/`) the export process will either fail or be compromised.
Our previous solution was to restrict the allowed characters in area names. However, this created incompatibilities with several simulations that had already been created by users in the past. We therefore decided to allow those characters again, but to sanitize them when generating the paths for the downloaded results (see https://github.com/gridsingularity/d3a-web/pull/1326)
> D3ASIM-3450: remove validation of area names

- tests/test_device_validator.py
- `unittest.subTest` can't be used with `pytest`, unless additional packages are employed (see [pytest docs](https://docs.pytest.org/en/6.2.x/unittest.html?highlight=subtest));
- `@pytest.mark.parametrize` and fixtures can't be used if the test class inherits from `unittest.TestCase`.
For these reasons, this PR refactors the unit tests for device validation to make a broader use of pytest, its assertions and its parametrized parameters.
> Refactor device validation tests using pytest

- d3a_interface/matching_algorithms/pay_as_clear_matching_algorithm.py
- tests/test_matching_algorithms/test_pay_as_clear_matching_algorithm.py
Fix a bug when sending multiple markets keys to the matcher
There is a test that should've checked this but there was a wrong expected data values
> Fix PAC multi markets matching

- d3a_interface/constants_limits.py
- d3a_interface/schemas.py
- d3a_interface/sim_results/device_statistics.py
- d3a_interface/validators/__init__.py
- d3a_interface/validators/smart_meter_validator.py
- tests/test_device_validator.py
This refactoring was asked by the stakeholders to homogenize our terminology to the energy market's.
> Refactoring: rename home meter to smart meter

- setup.cfg
- setup.py
Allow using bumpversion in this repository, without needing to manually add the tag.
> Fix bumpversion replacement

- gsy_framework/sim_results/kpi.py
We currently have two possible names for costs in the savings KPI: `d3a_cost` and `gsy_e_cost`. 
The `d3a_cost` key was replaced by `gsy_e_cost` and can therefore be missing. However, this check currently fails with a `KeyError` exception when the old `d3a_cost` key is not found.
This PR fixes the issue.
> Avoid KeyError when dealing with d3a_cost in savings KPI

- gsy_framework/sim_results/kpi.py
The fix implemented in #320 brought to light another issue with the computation of the `saving_absolute` value. This PR is an attempt to fix it.
> Avoid None values when retrieving savings costs

- gsy_framework/constants_limits.py
- gsy_framework/validators/storage_validator.py
- tests/test_device_validator.py
The "loss per hour" mechanism is being deprecated, so this PR removes all validations involving it.
- gridsingularity/gsy-e#1357
> GSYE-108: Remove Storage loss per hour mechanism

- gsy_framework/data_classes.py
- tests/test_dataclasses.py
In order to know the traded energy, we used to get it from `trade.offer_bid.energy`.
However,`energy` and `price` members of the bid and offer instances aren't the absolute source of truth now because if they have requirements they will be prioritized.
This PR adds `traded_energy` and `trade_price` members to the Trade object, so from now on we should read these values.
> GSYE-154: Add 'traded_energy' member to the 'Trade' dataclass

- gsy_framework/client_connections/utils.py
During my investigation, it turned out that the `RestCommunicationMixin._create_jwt_refresh_timer` thread is working fine.
The problem is that, before my change, it used to refresh tokens just `30` seconds before their expiration.
So, I guess that the related [issue](https://gridsingularity.atlassian.net/browse/GSYE-260) is talking about a situation which the gsy-e-sdk was not able to refresh the token in 30 seconds (probably because of network issues).
To address this problem, I suggest to increase the frequency of refreshing JWT tokens. For this purpose, I increased it to 3 times of refreshing during a tokens lifetime (48 * 3600 seconds) ~ refreshing every 12 hours.
> GSYE-260: Increased the frequency of refreshing JWT tokens

- gsy_framework/sim_results/__init__.py
- gsy_framework/sim_results/kpi.py
- tests/test_savings_kpi.py
This PR includes:
1. Removing the limit of exporting of savings KPI only for homes
2. Enable calculating of savings_percentage also for negative base costs
3. Fix treatment of battery in the savings KPI calculation 
4. Fix calculation of gsy_e_cost for producers
5. Accumulate all savings from children areas to the parent savings (which is the main task of this task)
6. Refactoring for better readability of the kpi.py module
> Feature/gsye 1 Enable exporting savings kpi for community areas 

- gsy_framework/sim_results/cumulative_grid_trades.py
This is a precautionary measure in a corner case of missing children key of area in accumulated_trades but the same time there are existed children in area configuration tree.
> GSYE-269: Set an empty list as a default children in accumulated_trades

- gsy_framework/sim_results/cumulative_grid_trades.py
The previous fix was only making the corrupted CN work, but is not needed for non-corrupted simulations. The code from this fix was also populating incorrect value for `cumulative_grid_trades` and caused problems later with `readSimulationResultsQuery`.
> GSYE-269: Revert unneeded children key assignment in accumulated_trades

- .pylintrc
- tests/test_read_user_profile.py
- Add test for `read_and_convert_identity_profile_to_float()`
- Fix tests for `read_arbitrary_profile()` (half of the tests were not running because of the GlobalConfig setup)
- Add exceptions to pylintrc for test docstrings
- Do not use unittest classes for the test module
> Implement new tests for read_user_profile

- gsy_framework/data_classes.py
- tests/test_dataclasses.py
According to [GSYE-159](https://gridsingularity.atlassian.net/browse/GSYE-159), in the past it was revealed that dynamically calculating `energy_rate` consumes a lot of CPU cycles, thus the decision was to pre-calculate and cache it. We guess the situation is different now and the frequency of using the `energy_rate` member has decreased, so we decided to replace it with a property to see if it has a significant increase in the simulation runtime. In case if an increase, it will be reverted.
- Replace `enerty_rate` member by a property
- Refactor `TestBaseBidOffer.test_to_json_string`
- Make Pylint happier!
INTEGRATION_TESTS_BRANCH=master
GSY_FRAMEWORK_BRANCH=master
> GSYE-159: Replace `energy_rate` with a property in BaseBidOffer

- gsy_framework/enums.py
`CloudCoverage` will be re-used by the community datasheet importer in the context of GSYE-261. More specifically, `CloudCoverage.LOCAL_GENERATION_PROFILE` will be used to populate the value of `"cloud_coverage"` in PV representations when they don't explicitly provide energy profiles.
- Move `CloudCoverage` to gsy-framework
- https://github.com/gridsingularity/gsy-web/pull/1732
- https://github.com/gridsingularity/gsy-backend-integration-tests/pull/54
> Move CloudCoverage enum to gsy-framework

- requirements/base.txt
- requirements/tests.txt
- Fix dependency name for backports-entry-points-selectable
> GSYE-364: Fix backports-entry-points-selectable==1.1.0 installation error

- gsy_framework/community_datasheet/community_datasheet_reader.py
openpyxl doesn't support old xls files:
> openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support the old .xls file format, please use xlrd to read this file, or convert it to the more recent .xlsx file format.
Passing a "plain" xls file to openpyxl correctly raises the expected `InvalidFileException`. However, passing an instance of django's `InMemoryUploadedFile` that refers to an xls raises a `BadZipFile` exception instead.
This PR refactors the code so that this `BadZipFile` exception is caught, to show the proper error (not the “Server Error” we currently have).
> Catch BadZipFile exception for datasheet unsupported xls files

- gsy_framework/sim_results/scm/kpi.py
As requested by [GSYE-418](https://gridsingularity.atlassian.net/browse/GSYE-418), the following KeyError is raised when calculating KPIs for the GridMarket.
Note: This is a temporary fix (That's why you see a #TODO) and all arguments of `SCMKPIState` should be mandatory as soon as frontend removed the `Grid Market` from the scenario. Also, gsy-web should take care of asserting that.
```python
Traceback (most recent call last):
File "/app/simulation_results/redis_results_subscription.py", line 58, in _simulation_results_handler
self.results_calculation.update_simulation_result(message)
File "/app/simulation_results/results_calculation_helper.py", line 42, in update_simulation_result
self._restore_state(data["configuration_tree"], data["job_id"])
File …
```
> GSYE-418: Fix SCMKPI raising KeyError exceptions for GridMarket

- gsy_framework/sim_results/electric_blue/aggregate_results.py
- gsy_framework/sim_results/electric_blue/timeseries_base.py
- gsy_framework/sim_results/electric_blue/volume_timeseries.py
- tests/test_sim_results/electric_blue/test_aggregate_results.py
- tests/test_sim_results/electric_blue/test_time_series.py
- tests/test_sim_results/electric_blue/test_volume_timeseries.py
As requested by [GSYE-414](https://gridsingularity.atlassian.net/browse/GSYE-414), we need to pre-calculate price profile in different resolutions for each asset.
Proposed changes:
- Refactor AssetVolumeTimeSeries into two classes (AssetVolumeTimeSeries & AssetTimeSeriesBase)
- Add price and energy_rate calculation to AssetVolumeTimeSeries
- Major refactor for unit tests
> feature/GSYE-414: Add calculatation of price profile graph

- gsy_framework/sim_results/all_results.py
As requested by [GSYE-445](https://gridsingularity.atlassian.net/browse/GSYE-445), we want to replace MarketEnergyBills with SCMBills for SCM simulations.
Old SCM bills format (for each area):
New SCM bills format (for each area):
> GSYE-445: Replace MarketEnergyBills with SCMBills for SCM simulations

- gsy_framework/data_classes.py
Followup of this https://github.com/gridsingularity/gsy-framework/pull/403/ , removes the already_tracked parameter from the Trade class.
> GSYE-441: Remove already_tracked parameter from the Trade class.
